/**
 * Default Metric & Column Definitions — used ONLY as the seed when the
 * DictionaryEntry collection is empty (first boot). At runtime, the
 * dictionary lives in Mongo and is editable via /api/admin/dictionary.
 *
 * To change definitions for an existing deployment: use the admin API.
 * To change the bootstrap defaults for a fresh deployment: edit this file.
 */

export const DEFAULT_DICTIONARY = [
  /* ══ Sales Performance ══ */
  { name: "month",    def: "Calendar month of the sales period (Jan–Jun)" },
  { name: "region",   def: "Sales territory: North, South, East, or West" },
  { name: "product",  def: "Product line sold: Widget A, Widget B, or Widget C" },
  { name: "channel",  def: "Sales channel: Online, Retail, or Wholesale" },
  { name: "revenue",  def: "Total revenue generated by the row's region/product/month combination (USD)" },
  { name: "units",    def: "Number of units sold in the period" },
  { name: "cost",     def: "Cost of goods sold for the period (USD); subtract from revenue to get gross profit" },
  { name: "returns",  def: "Number of product units returned by customers" },
  { name: "ad_spend", def: "Advertising spend allocated to the period (USD)" },

  /* ══ Customer Behavior ══ */
  { name: "week",            def: "Weekly time bucket (e.g. W1 Jan, W2 Feb)" },
  { name: "signups",         def: "New customer sign-ups in the week" },
  { name: "churn",           def: "Customers who cancelled or disengaged in the week" },
  { name: "active_users",    def: "Total active users at the end of the week" },
  { name: "avg_handle_time", def: "Average time (seconds) taken to resolve a support ticket" },
  { name: "nps",             def: "Net Promoter Score for the week (-100 to +100); higher is better" },
  { name: "tickets",         def: "Number of support tickets opened in the week" },
  { name: "resolution_rate", def: "Percentage of support tickets successfully resolved (%)" },

  /* ══ Financial Reports (Costs) ══ */
  { name: "department", def: "Business department: Engineering, Marketing, Sales, HR, or Finance" },
  { name: "category",   def: "Expense category: Salaries, Ad Spend, Travel, Benefits, or Audit" },
  { name: "Q1",         def: "Total spend for Q1 (January–March) in USD" },
  { name: "Q2",         def: "Total spend for Q2 (April–June) in USD" },
  { name: "Q3",         def: "Total spend for Q3 (July–September) in USD" },
  { name: "Q4",         def: "Total spend for Q4 (October–December) in USD" },
  { name: "headcount",  def: "Number of employees in the department" },

  /* ══ Customer Feedback ══ */
  { name: "date",   def: "Month the feedback was collected (e.g. Feb, Mar)" },
  { name: "text",   def: "Free-text customer feedback entry (qualitative, NLP-processed)" },

  /* ══ Derived / Computed KPIs (not direct columns but queryable) ══ */
  { name: "profit",          def: "Computed: revenue minus cost — gross profit for the period" },
  { name: "profit_margin",   def: "Computed: (revenue - cost) / revenue × 100 — gross margin %" },
  { name: "return_rate",     def: "Computed: returns / units × 100 — percentage of units returned" },
  { name: "churn_rate",      def: "Computed: churn / active_users × 100 — weekly churn percentage" },
  { name: "cost_per_signup", def: "Computed: ad_spend / signups — customer acquisition cost proxy" },
];
